function B = LinearizedRHO(thrusters, numThrusters)

global G_EARTH

if numThrusters == 12
    
    B = ones(1,numThrusters);

    mass_dot = - 1 / ...
            ( thrusters(1).isp * G_EARTH );

    rho_dot = mass_dot/...
        (...
        (thrusters(1).structureDim(1,2) ...
        - thrusters(1).structureDim(1,1)) ...
        * (thrusters(1).structureDim(2,2) ...
        - thrusters(1).structureDim(2,1)) ...
        * (thrusters(1).structureDim(3,2) ...
        - thrusters(1).structureDim(3,1)) ...
        );

    B = rho_dot.*B;
            
else
    
    B = zeros(numThrusters);

    for propIter = 1:numThrusters

            mass_dot = - 1 / ...
                ( thrusters(propIter).isp * G_EARTH );

            rho_dot = mass_dot/...
                (...
                (thrusters(propIter).structureDim(1,2) ...
                - thrusters(propIter).structureDim(1,1)) ...
                * (thrusters(propIter).structureDim(2,2) ...
                - thrusters(propIter).structureDim(2,1)) ...
                * (thrusters(propIter).structureDim(3,2) ...
                - thrusters(propIter).structureDim(3,1)) ...
                );

            B(propIter,propIter) = rho_dot;

    end

end


end

