function B = LinearizedRHO(thrusters)

global G_EARTH

B = zeros(length(thrusters));

for propIter = 1:length(thrusters)
    
        mass_dot = - 1 / ...
            ( thrusters(propIter).isp * G_EARTH );
        
        rho_dot = mass_dot/...
            (...
            (thrusters(propIter).structureDim(1,2) ...
            - thrusters(propIter).structureDim(1,1)) ...
            * (thrusters(propIter).structureDim(2,2) ...
            - thrusters(propIter).structureDim(2,1)) ...
            * (thrusters(propIter).structureDim(3,2) ...
            - thrusters(propIter).structureDim(3,1)) ...
            );
        
        B(propIter,propIter) = rho_dot;
        
end

