function [ R ] = RotMat_PQWToECI( i, O, w )

R = [-sin( O ) * cos( i ) * sin( w ) + cos( O ) * cos( w ), ...
    -sin( O ) * cos( i ) * cos( w ) - cos( O ) * sin( w ),  ...
    sin( O ) * sin( i ); ...
     cos( O ) * cos( i ) * sin( w ) + sin( O ) * cos( w ), ...
     cos( O ) * cos( i ) * cos( w ) - sin( O ) * sin( w ), ...
     -cos( O ) * sin( i );
     sin( i ) * sin( w ), sin( i ) * cos( w ), cos( i )];

end

