function B = LinearizedPROP( I_mat, com_struct, thrusters )

B = I_mat \ [ S_crossProdMat( thrusters(1).structArm - com_struct) * ...
    ( - thrusters(1).structureThrustDir ), ...
    S_crossProdMat( thrusters(2).structArm - com_struct) * ...
    ( - thrusters(2).structureThrustDir ), ...
    S_crossProdMat( thrusters(3).structArm - com_struct) * ...
    ( - thrusters(3).structureThrustDir ), ...
    S_crossProdMat( thrusters(4).structArm - com_struct) * ...
    ( - thrusters(4).structureThrustDir ), ...
    S_crossProdMat( thrusters(5).structArm - com_struct) * ...
    ( - thrusters(5).structureThrustDir ), ...
    S_crossProdMat( thrusters(6).structArm - com_struct) * ...
    ( - thrusters(6).structureThrustDir ) ];

end

